package ru.itis.summerpractice.uiandroid.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp


@Composable
fun FirstScreen(onNavigateToSecond: () -> Unit) {
    // Храним введенный текст
    var inputText by remember { mutableStateOf("") }

    // Флаг: сгенерирован ли список (нужен для активации второй кнопки)
    var isListGenerated by remember { mutableStateOf(false) }

    // Проверяем, введено ли валидное положительное число больше 0
    val count = inputText.toIntOrNull()
    val isCountValid = count != null && count > 0

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        // Текстовое поле для ввода числа
        OutlinedTextField(
            value = inputText,
            onValueChange = { newValue ->
                // Разрешаем вводить только цифры
                if (newValue.all { it.isDigit() }) {
                    inputText = newValue
                }
            },
            label = { Text("Введите количество фильмов") },
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))

        // Кнопка 1: Сгенерировать. Активна, только если число корректно
        Button(
            onClick = {
                if (count != null) {
                    DataRepository.generateFilms(count)
                    isListGenerated = true
                }
            },
            enabled = isCountValid,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Сгенерировать")
        }

        Spacer(modifier = Modifier.height(8.dp))

        // Кнопка 2: Переход на второй экран. Активна, только если список уже сгенерирован
        Button(
            onClick = { onNavigateToSecond() },
            enabled = isListGenerated,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Открыть второй экран")
        }
    }
}